set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports led_behavioral]
set_property IOSTANDARD LVCMOS33 [get_ports led_data]
set_property IOSTANDARD LVCMOS33 [get_ports led_gate]
set_property IOSTANDARD LVCMOS33 [get_ports SEL]

set_property PACKAGE_PIN V17 [get_ports A]
set_property PACKAGE_PIN V16 [get_ports B]
set_property PACKAGE_PIN W16 [get_ports SEL]
set_property PACKAGE_PIN U16 [get_ports led_gate]
set_property PACKAGE_PIN E19 [get_ports led_data]
set_property PACKAGE_PIN U19 [get_ports led_behavioral]
